image: docker:stable

.python_build: &python_build
  "cd python && 
  docker build --pull --build-arg TAG=${TAG}
  -f ${DOCKERFILE}
  -t ${PYTHON_IMAGE}:${TAG} . &&
  docker push ${PYTHON_IMAGE}:${TAG}"

variables:
  PYTHON_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/python

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

py-3.6-alpine:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-alpine
    TAG: 3.6-alpine
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.7-alpine:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-alpine
    TAG: 3.7-alpine
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.8-alpine:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-alpine
    TAG: 3.8-alpine
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.9-alpine:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-alpine
    TAG: 3.8-alpine
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.6-slim-stretch:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-debian-slim
    TAG: 3.6-slim-stretch
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.7-slim-stretch:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-debian-slim
    TAG: 3.7-slim-stretch
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.6-slim-buster:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-debian-slim
    TAG: 3.6-slim-buster
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.7-slim-buster:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-debian-slim
    TAG: 3.7-slim-buster
  script: *python_build
  only:
    - schedules
  tags:
    - docker

py-3.8-slim-buster:
  stage: build
  variables:
    DOCKERFILE: Dockerfile-debian-slim
    TAG: 3.8-slim-buster
  script: *python_build
  only:
    - schedules
  tags:
    - docker
