ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-alpine

WORKDIR /app
ENV PATH="/root/.poetry/bin:$PATH"

RUN apk add --no-cache \
    build-base \
    gcc \
    libffi-dev \
    openssl-dev \
    libxslt-dev \
    yaml-dev \
    curl \
    git \
    && curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python \
    && python -m venv .venv \
    && poetry config settings.virtualenvs.in-project true \
    && .venv/bin/pip install --no-cache-dir -U pip setuptools \
    && mkdir /ntc-templates \
    && curl -sL https://github.com/networktocode/ntc-templates/archive/master.tar.gz \
    | tar --strip-components=1 -zx -C /ntc-templates
