ARG TAG
FROM python:${TAG}

WORKDIR /app
ENV POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    POETRY_VIRTUALENVS_IN_PROJECT=1

ARG DEPS="curl git make"

RUN apt-get update \
 && apt-get install -yq ${DEPS} --no-install-recommends \
 && sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin \
 && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - \
 && rm -rf /var/lib/apt/lists/*
