ARG TAG
FROM ${TAG}

LABEL org.opencontainers.image.source="https://github.com/dmfigol/base-docker-images"
LABEL maintainer="git@dmfigol.me"

WORKDIR /app
ENV POETRY_HOME="/opt/poetry" \
    PATH="/opt/poetry/bin:$PATH" \
    POETRY_VIRTUALENVS_IN_PROJECT=1

ARG DEPS="curl git make"

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -yq ${DEPS} --no-install-recommends \
 && sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin \
 && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
