name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 3,6" # every Wednesday, Saturday at 4AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: python
          file: python/Dockerfile-debian-slim
          push: true
          tags: ghcr.io/dmfigol/base-docker-images/python:3.8-slim
          build-args: |
            TAG=3.8-slim

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
