name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 3,6" # every Wednesday, Saturday at 4AM UTC

env:
  REGISTRY: ghcr.io

jobs:
  python:
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11", "3.12"]
        base: ["slim"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: python
          file: python/Dockerfile-${{ matrix.base }}
          platforms: linux/amd64,linux/arm64
          push: true
          pull: true
          tags: ${{ env.REGISTRY }}/dmfigol/base/python:${{ matrix.py-version }}-${{ matrix.base }}
          build-args: |
            TAG=python:${{ matrix.py-version }}-${{ matrix.base }}
