name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 3,6" # every Wednesday, Saturday at 4AM UTC

jobs:
  python:
    strategy:
      matrix:
        py-version: ["3.6", "3.7", "3.8", "3.9"]
        base: ["slim", "alpine"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: python
          file: python/Dockerfile-${{ matrix.base }}
          push: true
          tags: ghcr.io/dmfigol/base/python:${{ matrix.py-version }}-${{ matrix.base }}
          build-args: |
            TAG=python:${{ matrix.py-version }}-${{ matrix.base }}
