name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * 3,6" # every Wednesday, Saturday at 4AM UTC

jobs:
  python:
    strategy:
      matrix:
        args:
          - ["python:3.6-slim", "python/Dockerfile-slim"]
          - ["python:3.7-slim", "python/Dockerfile-slim"]
          - ["python:3.8-slim", "python/Dockerfile-slim"]
          - ["python:3.9-slim", "python/Dockerfile-slim"]
          - ["python:3.6-alpine", "python/Dockerfile-alpine"]
          - ["python:3.7-alpine", "python/Dockerfile-alpine"]
          - ["python:3.8-alpine", "python/Dockerfile-alpine"]
          - ["python:3.9-alpine", "python/Dockerfile-alpine"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: python
          file: ${{ matrix.args[1] }}
          push: true
          tags: ghcr.io/dmfigol/base/${{ matrix.args[0] }}
          build-args: |
            TAG=${{ matrix.args[0] }}
