on:
  schedule:
    - cron: "0 4 * * 3,6" # every Wednesday, Saturday at 4AM UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: python
          file: python/Dockerfile-debian-slim
          push: true
          tags: dmfigol/python:3.8-slim
          build-args: |
            TAG=3.8-slim
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
